# Команда, яка виконається від імені консолі при убийстві босса
reward-command: "p give %player% 100"

# Список часу, коли івент запускається автоматично (формат HH:mm)
event-times:
  - "12:00"
  - "15:00"
  - "18:00"
  - "21:00"

messages:
  prefix: "&8[&6BossBee&8]"
  start: "&fИвент начався на координатах &e%loc%&f!"
  stop: "&fВсе боссы повержены, ивент окончен."
  reward: "&aВы получили награду за убийство босса!"
  delay: "&fДо следующего ивента: &e%h% ч. %m% мин."
  boss-name: "&6Пчела-Босс"

# Дані про локацію спавну (заповнюються автоматично через /bossbea setspawn)
spawn:
  world: "world"
  x: 0.0
  y: 0.0
  z: 0.0